estores/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask import current_app
from flask_login import AnonymousUserMixin
from . import db, login_manager

class Permission:
    RECIV_ORDERS = 0x01
    MANAGE_PRODUCTS = 0x02
    MANAGE_ESTABLISHMENTS = 0x04
    ADMINISTER = 0x80

class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False

    def is_administrator(self):
        return False

login_manager.anonymous_user = AnonymousUser

class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    vendors = db.relationship('Vendor', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role %r>' % self.name

    @staticmethod
    def insert_roles():
        roles = {
            'Vendor': (Permission.MANAGE_PRODUCTS | Permission.MANAGE_ESTABLISHMENTS, True),
            'Deliverer': (Permission.RECIV_ORDERS, False),
            'Administrator': (0xff, False),
        }
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.permissions = roles[r][0]
            role.default = roles[r][1]
            db.session.add(role)
        db.session.commit()

class Vendor(db.Model):
    __tablename__ = 'vendors'
    vid = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), index=True, unique=True)
    pword_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    name = db.Column(db.String(64))
    contact_no = db.Column(db.Numeric(11))
    address = db.Column(db.String(64))
    img_src = db.Column(db.String(64))
    member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    establishment_count = db.Column(db.Integer, default=1)
    establishments = db.relationship('Establishment', backref='vendor', lazy='dynamic')

    def __init__(self, **kwargs):
        super(Vendor, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['FLASKY_ADMIN']:
                self.role = Role.query.filter_by(permissions=0xff).first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()

    def __repr__(self):
        return '<Vendor %r>' % self.name

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.pword_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pword_hash, password)

    def can(self, permissions):
        return self.role is not None and (self.role.permissions & permissions) == permissions

    def is_administrator(self):
        return self.can(Permission.ADMINISTER)

    @property
    def is_authenticated(self):
        return True

    @property
    def is_active(self):
        return True

    @property
    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.vid)

class Establishment(db.Model):
    __tablename__ = 'establishments'
    eid = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    address = db.Column(db.String(64))
    etype = db.Column(db.String(64))
    img_src = db.Column(db.String(64))
    vid = db.Column(db.Integer, db.ForeignKey('vendors.vid'))
    sales = db.relationship('Sale', backref='establishment', lazy='dynamic')

    def __repr__(self):
        return '<Establishment %r>' % self.name

class Stock(db.Model):
    __tablename__ = 'stocks'
    eid = db.Column(db.Integer, db.ForeignKey('establishments.eid'), primary_key=True)
    prod_id = db.Column(db.Integer, db.ForeignKey('products.prod_id'), primary_key=True)
    availability = db.Column(db.Boolean, default=True)

class Product(db.Model):
    __tablename__ = 'products'
    prod_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    description = db.Column(db.Text)
    category = db.Column(db.String(64))
    prod_type = db.Column(db.String(64))
    price = db.Column(db.Float)
    img_src = db.Column(db.String(64))

    def __repr__(self):
        return '<Product %r>' % self.name

class SalesDetail(db.Model):
    __tablename__ = 'salesdetails'
    prod_id = db.Column(db.Integer, db.ForeignKey('products.prod_id'), primary_key=True)
    sales_id = db.Column(db.Integer, db.ForeignKey('sales.sales_id'), primary_key=True)
    quantity = db.Column(db.Integer, default=0)

class Sale(db.Model):
    __tablename__ = 'sales'
    sales_id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime(), default=datetime.utcnow)
    sum_total = db.Column(db.Float)
    customer_id = db.Column(db.Integer, db.ForeignKey('customers.customer_id'))
    eid = db.Column(db.Integer, db.ForeignKey('establishments.eid'))
    delivery_id = db.Column(db.Integer, db.ForeignKey('deliveries.delivery_id'))

    def __repr__(self):
        return '<Sale %r>' % self.sales_id

class Customer(db.Model):
    __tablename__ = 'customers'
    customer_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    address = db.Column(db.String(64))
    mobile_no = db.Column(db.Numeric(11))
    sales = db.relationship('Sale', backref='customer', lazy='dynamic')

    def __repr__(self):
        return '<Customer %r>' % self.name

class Delivery(db.Model):
    __tablename__ = 'deliveries'
    delivery_id = db.Column(db.Integer, primary_key=True)
    provider = db.Column(db.String(64))
    provider_contact_no = db.Column(db.Numeric(11))
    provider_address = db.Column(db.String(64))
    delivery_person = db.Column(db.String(64))
    delivery_contact_no = db.Column(db.Numeric(11))
    sales = db.relationship('Sale', backref='delivery', lazy='dynamic')

    def __repr__(self):
        return '<Delivery %r>' % self.provider

estores/main/forms.py
from flask_wtf import FlaskForm
from wtforms import ValidationError, StringField, SubmitField
from wtforms.validators import DataRequired, Length, Regexp
from ..models import Role, Vendor, Establishment

class VendorProfileForm(FlaskForm):
    name = StringField('Full Name', validators=[Length(0, 64)])
    contact_no = StringField('Contact Number', validators=[DataRequired(), Regexp('^[0-9]+$', 0, '11-digit mobile number must consist of numbers only')])
    address = StringField('Home Address', validators=[Length(0, 64)])
    img_src = StringField('Picture')
    #submit = SubmitField('Update')

class EstablishmentProfileForm(FlaskForm):
    name = StringField('Establishment Name', validators=[Length(0, 64)])

estores/__init__.py
from flask import Flask
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_assets import Environment
from config import config
from .util.assets import bundles

moment = Moment()
db = SQLAlchemy()
assets = Environment()
assets.register(bundles)
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
#login_manager.login_message = 'Please Log In to access your requested page.'

def create_app(config_name):
    app = Flask(__name__, static_url_path='/static')
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    assets.init_app(app)

    from .models import Vendor
    @login_manager.user_loader
    def load_user(vid):
        return Vendor.query.get(int(vid))

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .accounts import accounts as accounts_blueprint
    app.register_blueprint(accounts_blueprint)

    return app

estores/accounts/__init__.py
from flask import Blueprint

accounts = Blueprint('accounts', __name__)

from . import views

estores/accounts/views.py
from flask import current_app, render_template
from flask_login import login_required
from . import accounts

@accounts.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    return render_template('accounts/dashboard.html')

@accounts.route('/profile', methods=['GET'])
@login_required
def profile():
    return render_template('accounts/profile.html')

@accounts.route('/settings', methods=['GET'])
@login_required
def settings():
    return render_template('accounts/settings.html')

estores/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors
from ..models import Permission

@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

estores/main/views.py
from flask import current_app, render_template, url_for, redirect
from flask_login import current_user
from . import main

@main.route('/', methods=['GET'])
def index():
    return render_template('main/index.html')

estores/templates/layout.html
<!DOCTYPE html>
<html lang="en" style="height: 100%;">
    <head>
        {% block head %}

        <title>{% block title %}{% endblock %}</title>

        {% assets "uikit_css" %}
            <link rel="stylesheet" href="{{ ASSET_URL }}" />
        {% endassets %}
        {% assets "uikit_js" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}

        {% endblock %}
    </head>
    <body style="position: relative; min-height: 100%; top: 0px;">
        {% block body %}

        <div class="uk-offcanvas-content">
            <div uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky;">
            <nav class="uk-navbar-container uk-light" uk-navbar="mode: click">
                <div class="uk-navbar-left">
                    <div class="uk-navbar-item">
                        <div><a class="uk-navbar-item uk-logo" href="{{ url_for('main.index') }}">Logo</a></div>
                    </div>

                    <ul class="uk-navbar-nav uk-visible@m">
                        <li><a href="#">Active</a></li>
                        <li>
                            <a href="#">Parent</a>
                            <div class="uk-navbar-dropdown">
                                <ul class="uk-nav uk-navbar-dropdown-nav">
                                    <li class="uk-active"><a href="#">Active</a></li>
                                    <li><a href="#">Item</a></li>
                                    <li><a href="#">Item</a></li>
                                </ul>
                            </div>
                        </li>
                        <li><a href="#">Item</a></li>
                    </ul>
                </div>

                <div class="uk-navbar-right">
                    <a class="uk-navbar-toggle uk-hidden@m" uk-navbar-toggle-icon href="#offcanvas-menu" uk-toggle></a>

                    <div class="uk-navbar-item uk-visible@m">
                        <div>
                            <a class="uk-button uk-button-text" href="#">
                                <span class="uk-icon" uk-icon="icon: cart"></span>
                                Cart
                            </a>
                        </div>
                    </div>
                    <div class="uk-navbar-item uk-visible@m">
                        {% if current_user.is_authenticated %}
                            <div><button class="uk-button uk-button-text" type="button">{{ current_user.email }}</button></div>
                            <div uk-dropdown="mode: click">
                                <ul class="uk-nav uk-dropdown-nav">
                                    <li class="uk-nav-header">{{ current_user.name }}</li>
                                    <li><a href="{{ url_for('accounts.dashboard') }}">Dashboard</a></li>
                                    <li><a href="{{ url_for('accounts.profile') }}">Profile</a></li>
                                    <li><a href="{{ url_for('accounts.settings') }}">Settings</a></li>
                                    <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                                </ul>
                            </div>
                        {% else %}
                            <div><a class="uk-button uk-button-text" href="{{ url_for('auth.login') }}">Login</a></div>
                        {% endif %}
                    </div>
                </div>
            </nav>
            </div>
          <div class="body-navbar">
          </div>

          <div class="body-content">
            {% block content %}
            {% endblock %}
          </div>

            {% block scripts %}
            {% endblock %}
        </div>

        {% endblock %}
    </body>
</html>